### PR TITLE
use standard iterator for Stack + Queue Fixes #116

### LINKED ISSUE #116: Stacks and Queues should work in for loops
Right now Deque works in for loops, but Stacks and Queues don't

```Julia
using DataStructures

s = Stack(Int)
q = Queue(Int)
deq  = Deque{Int}()

for x in deq println(x) end
``` 
works
 
but 
```Julia 
for x in s println(x) end
ERROR: `start` has no method matching start(::Stack{Deque{Int64}})
 in anonymous at no file

julia> for x in q  println(x) end
ERROR: MethodError: `start` has no method matching start(::DataStructures.Queue{DataStructures.Deque{Int64}})
 in anonymous at no file
```

I think this is because Stack and Queue, while building on Deque, don't redefine next() etc required for iteration. I thought they'd use the underlying Deque's itrerator protocol [1], but apparently not.

[1]which would still be wrong for one of Stack or Queue or both -if Deque uses random access for iteration - Stack iteration should be LIFO and Queue should have FIFO iteration

### PR DESCRIPTION
**Pull request by rawls238**
@kmsquire

This moves the iterator for stack and queue to conform to iterators such as those in https://github.com/JuliaLang/Iterators.jl

It effectively just calls down and utilizes the iterator for `Deque`

### CODE REVIEW

**Comment by kmsquire** [comment]
Okay, seems mostly reasonable to me.  

Because the `iter` interface was released (even if only for a short time), it should probably go through a period of deprecation.  I'm not sure the standard deprecation interface will work, here.  Try it (see #161), and if it doesn't work, print a warning using `Base.warn_once`.

If you haven't yet, look at the discussion in #116 (which probably could be closed).  That's discussion is the reason that the interface is the way it is now.  I think if we're going to go the route suggested there, it should be planned out better (`iter` doesn't seem like the best name to me).  So I'm inclined to do this first, which is simpler--additional iterators can always be added later.

Cc: @lindahua @RaviMohan

**Comment by kmsquire** [comment]
(And of course, you noted that this fixes #116 in this PR, so you obviously saw that...)

Anyway, thanks for the PR!

**Comment by rawls238** [comment]
@kmsquire I saw the discussion there, though I think I was wrong in removing the `iter` method here after re-reading and rethinking. I think we should encapsulate the default iterator behavior by defaulting to the standard Julia iterator interface (and have an implementation that doesn't make a copy of the underlying object), but for both of these types allows a `forward_iter` and a `backward_iter` method which follows the same interface as the `iter` method. Thoughts on that approach?

**Comment by kmsquire** [comment]
I think that sounds good.  I wouldn't copy the `iter` method though.  Instead I would create `immutable ForwardDequeIterator` and `BackwardDequeIterator` types and use these for iterating `Stacks`, `Queues`, and `Deques`.  That would be cleaner than copying the underlying data that iter is doing now.

`Iterators.jl` mostly uses this paradigm.

**Comment by rawls238** [comment]
@kmsquire let me know what you think of this - I ended up using `Tasks` to implement the forward and backward iters + made the default iterator for stack be LIFO and the default iterator for queue be FIFO

**Comment by kmsquire** [comment]
Hi @rawls238, unfortunately, while it seems elegant, using `Tasks` is probably not the way to go.  The quickest showstopper is

```julia
julia> y
DataStructures.Stack{Int64}(Deque [[28,83,82,77,61,53,17,13,73,51]])

julia> [i for i in forward_iter(y)]
ERROR: MethodError: `length` has no method matching length(::Task)
 in anonymous at no file
```

Since a Task is not parameterized by what it wraps, there's no way to define that function either.

I'll add a few other comments inline.

File: src/DataStructures.jl [hunk 1]
```diff
@@ -14,11 +14,11 @@ module DataStructures
                  ReverseOrdering, Reverse, Lt,
                  isless,
                  union, intersect, symdiff, setdiff, issubset,
-                 find, searchsortedfirst, searchsortedlast, endof, in
+                 find, searchsortedfirst, searchsortedlast, endof, in, produce
 
 
     export Deque, Stack, Queue
-    export deque, enqueue!, dequeue!, update!,iter
+    export deque, enqueue!, dequeue!, update!, forward_iter, backward_iter
```
Comment (kmsquire) [inline src/DataStructures.jl]: In other areas of julia, `reverse` is used instead of `backward`.  While `backward` isn't wrong, it would  be nice to be consistent.

File: src/DataStructures.jl [hunk 2]
```diff
@@ -94,4 +94,7 @@ module DataStructures
     export status
     export deref_key, deref_value, deref, advance, regress
 
+    @deprecate iter Stack
+    @deprecate iter Queue
+
```
Comment (kmsquire) [inline src/DataStructures.jl]: :+1:

Comment (kmsquire) [inline src/DataStructures.jl]: Whoops... no, this probably isn't right, actually...

File: src/DataStructures.jl (hunk 1 above)
Comment (kmsquire) [inline src/DataStructures.jl]: Although now that I say that, none of these is particularly clear for stacks, at least (because forward or backward/reverse depends on the implementation).

**Comment by kmsquire** [comment]
Not going to have time to look at this closer right now, and the implementation is going to take some thought.  I'll try to write more later.

File: src/DataStructures.jl (hunk 1 above)
Comment (rawls238) [inline src/DataStructures.jl]: see the discussion in the corresponding issue. I was using `backward_iter` as the name from the discussion there, happy to change to `reverse_iter`, though for reasons described below I think this may not be the best idea.

Currently, the default iterator uses LIFO order for stacks and FIFO for queues, whereas `forward_iter` is always FIFO and `backward_iter` is always LIFO.  I think it makes sense for the default iterator to use the ordering that makes sense for the particular data structure whereas the separate functions for `forward_iter` and `backward_iter` should be consistent across data structures (and the term backward versus reverse in the case would make more sense). Let me know what you think about that

File: src/DataStructures.jl (hunk 2 above)
Comment (rawls238) [inline src/DataStructures.jl]: hm, was looking at the diff here since I've never used this macro, should it just be `@deprecate iter`?

**Comment by rawls238** [comment]
hm, good point around why `Tasks` won't be ideal here. Going to think of how to do this in an alternative way - let me know if you have any ideas

File: src/DataStructures.jl (hunk 2 above)
Comment (kmsquire) [inline src/DataStructures.jl]: This should do it:

```julia
@deprecate iter(s::Stack) backward_iter(s)
@deprecate iter(q::Queue) forward_iter(q)
```

Plenty of examples [here](https://github.com/JuliaLang/julia/blob/master/base/deprecated.jl#L104).

File: src/DataStructures.jl (hunk 1 above)
Comment (kmsquire) [inline src/DataStructures.jl]: @lindahua, who introduced those names, is coming from a C++ background, and in C++, the corresponding iterators are `forward_iterator` and `backward_iterator`. 

Thinking more, I would actually prefer that, instead, we had a natural order iterator (the default), and a second, `reverse_iter`, which is just opposite of the default iteration.  Reasons:

1. It's easier to reason about--you don't have to understand how the underlying data structure is implemented, you only have to understand its default iteration order.
2. At one point, a generic `reverse` iterator (and corresponding `Reverse` type) was implemented this way in Julia (it was later changed to return a concrete value).
3. It's one less function to create.

File: src/deque.jl [hunk 3]
```diff
@@ -123,6 +123,40 @@ end
...
 
+# Backwards deque iteration
+
+immutable BackwardDequeIterator{T}
+    is_done::Bool
+    cblock::DequeBlock{T}  # current block
+    i::Int
+end
+
+start_backward{T}(q::Deque{T}) = BackwardDequeIterator{T}(isempty(q), q.rear, q.head.back)
```
Comment (kmsquire) [inline src/deque.jl]: `q.head.back` should be `q.rear.back`, right?

**Comment by kmsquire** [comment]
@rawls238, check out #177.  This would be my preference for Deque iteration, and it might give you some ideas for the rest of this PR.  (Comments welcome in #177!)

**Comment by rawls238** [comment]
thanks @kmsquire, I built off your work there and made some changes in here. Will make some comments inline

File: src/DataStructures.jl (hunk 1 above)
Comment (rawls238) [inline src/DataStructures.jl]: I modified things such that there are is a `DequeIterator` and a `ReverseDequeIterator` but the default iteration order is the `DequeIterator` for the deque object (i.e. if you just do
```
for i in dq
  println(i)
end
```

it iterates in the order you expect it to). I still think it makes sense to define a `forward_iter` method which can optionally be used to get objects in a FIFO ordering and a `reverse_iter` method which can optionally be used to get objects in a LIFO ordering. `Deque`, `Stack`, and `Queue` have their default iteration order defined as FIFO, LIFO, and FIFO respectively and in most cases people should just use their default iteration order (perhaps to make this clearer we should have the `iter` function which returns the default iteration order for the particular type - generally I think most people would use the conventional iterator syntax `for i in q` as opposed to `for i in forward_iter(q)`), but if you particularly want things in LIFO order then you would use `reverse_iter` (and vice versa for FIFO order).

Let me know if you think that's simply overcomplicating things. Also, regardless of the direction we take, we should document this behavior clearly.

Comment (rawls238) [inline src/DataStructures.jl]: actually I like the idea of leaving iter but having it return the default iterator for the type

File: src/deque.jl [hunk 4]
```diff
@@ -93,45 +96,70 @@ end
...
+    q::Deque
 end
 
-start{T}(q::Deque{T}) = DequeIterator{T}(isempty(q), q.head, q.head.front)
-
-function next{T}(q::Deque{T}, s::DequeIterator{T})
-    cb = s.cblock
-    i::Int = s.i
-    x::T = cb.data[i]
+start{T}(qi::DequeIterator{T}) = (qi.q.head, qi.q.head.front)
```
Comment (rawls238) [inline src/deque.jl]: @kmsquire I also applied your cleanups to the existing iterator

File: src/stack.jl [hunk 5]
```diff
@@ -17,13 +17,12 @@ function push!(s::Stack, x)
...
-        unshift!(a,i)
-    end
-    return a
-end
-
 pop!(s::Stack) = pop!(s.store)
+
+start(st::Stack) = start_reverse(st.store)
+next(st::Stack, s) = next_reverse(st.store, s)
+done(st::Stack, s) = done_reverse(st.store, s)
```
Comment (kmsquire) [inline src/stack.jl]: I think I would just do

```julia
start(st::Stack) = start(reverse_iter(st.store))
next(st::Stack, s) = next(reverse_iter(st.store), s)
done(st::Stack, s) = done(reverse_iter(st.store), s)
```

and then remove `start_reverse`, `next_reverse`, and `done_reverse`.

The compiler should inline these, so they should produce the same code.

**Comment by kmsquire** [comment]
Nice update!

My preference, again, is to remove `forward_iter`, and make `reverse_iter` always produce the opposite of the default iterator.

So, for example, the default `Stack` iterator would go from the end of storage toward the beginning, and `reverse_iter` would produce the reverse of the default sequence (which, in this case, would go from the beginning of the underlying storage toward the end).  (This is the opposite of what you have now.)

The main idea is that `reverse` is not defined in terms of the underlying storage, but in terms of the expected behavior of the iterator.

I also think that `iter` should actually be deprecated.

@DanielArndt @lindahua any thoughts/opinion on this?

**Comment by kmsquire** [comment]
@rawls238, in my email, I see a couple of other responses from you (where you argue the opposite point of view), but I don't see those comments here.  Can you point them out, or repost them?

**Comment by kmsquire** [comment]
Cc: @StefanKarpinski, who might have an opinion about reverse iteration.

**Comment by DanielArndt** [comment]
@kmsquire Are you looking for this discussion? https://github.com/JuliaLang/DataStructures.jl/pull/171#discussion_r52119946

**Comment by DanielArndt** [comment]
@kmsquire Re: iterators, I agree that `iter` and `reverse_iter` should semantically make sense, and therefore `reverse_iter` should in fact iterate `iter` in reverse. It seems natural to me that `iter` would iterate according to what you expect from the of the data structure, as you suggested.

That being said, I am curious if there would be value in having a way to specifically specify that you would like a FIFO or FILO iterator which is what I think @rawls238 is suggesting. It definitely seems like a much less common use case.

**Comment by rawls238** [comment]
Yes that's what I'm suggesting, but I can see the appeal in just having the default iterator and reverse iterator since that simplifies things versus the approach I decided to take and makes it so that you don't have to think about the internals of stack and queue in order to decide what iterator to use (you just need to know the default iteration order for the particular data structure which should be documented). Unless anyone else thinks having explicit LIFO / FIFO iterators is a good idea, I'll change this to follow the default / reverse pattern.

**Comment by rawls238** [comment]
@kmsquire decided to just switch this to the interface you described. Also added a blurb in the docs about the iterators, let me know if you think this is good to go

File: doc/source/stack_and_queue.rst [hunk 6]
```diff
@@ -20,3 +20,5 @@ Usage of Queue::
   x = front(q)
   x = back(q)
   x = dequeue!(q)
+
+Both ``Stack`` and ``Queue`` implement the Iterator interface; iterating over ``Stack`` returns items in FILO order and iterating over ``Queue`` returns items in FIFO order. There is also a ``reverse_iter`` function implemented for both which returns items in the reverse order for each type (i.e. FIFO for ``Stack`` and FILO for ``Queue``).
```
Comment (kmsquire) [inline doc/source/stack_and_queue.rst]: I've always seen `FILO` written as `LIFO`...

File: src/DataStructures.jl [hunk 7]
```diff
@@ -94,4 +94,6 @@ module DataStructures
     export status
     export deref_key, deref_value, deref, advance, regress
 
+    @deprecate iter(s::Stack) collect(s)
+    @deprecate iter(q::Queue) collect(q)
```
Comment (kmsquire) [inline src/DataStructures.jl]: I wonder... `collect` does do essentially what `iter` used to do, so if someone used `iter` expecting an array, then this is correct.  However, if they're using `iter` to iterate over the stack or queue, then `collect(s)` and `collect(q)` should just be `s` and `q`...

File: src/queue.jl [hunk 8]
```diff
@@ -20,10 +20,19 @@ end
...
+
+reverse_iter(q::Queue) = reverse_iter(q.store)
+
+
+function iter{T}(s::Stack{T})
     a = T[]
-    for i in q.store
-        push!(a,i)
+    for i in s.store
+        unshift!(a,i)
```
Comment (kmsquire) [inline src/queue.jl]: I think you forgot to remove this function.  (Also not sure why the type was changed to `Stack`.)

**Comment by kmsquire** [comment]
Other than those comments, LGTM.

File: doc/source/stack_and_queue.rst (hunk 6 above)
Comment (DanielArndt) [inline doc/source/stack_and_queue.rst]: That's my fault! I started mix matching a few things yesterday. A good sign that one needs more sleep.

Comment (rawls238) [inline doc/source/stack_and_queue.rst]: heh yea I also thought this was strange, but the docs already were using `FILO` so I figured I would follow them here. I'll switch everything in this file to `LIFO`

File: src/DataStructures.jl (hunk 7 above)
Comment (rawls238) [inline src/DataStructures.jl]: yea, I was thinking the same thing - not sure which is the best way to go but I suppose just using `s` and `q` is probably best since that's the behavior we'll want to enforce going forward.

File: src/queue.jl (hunk 8 above)
Comment (rawls238) [inline src/queue.jl]: good catch

File: src/DataStructures.jl (hunk 7 above)
Comment (DanielArndt) [inline src/DataStructures.jl]: It makes sense to me that the deprecation leads you to similar functionality (`collect`). Worst case scenario, the developer has something a little less efficient that is well documented elsewhere.

The alternative (just suggesting `s` or `q`) is that the developer is directed to something that likely wouldn't work in some scenarios.

That is, unless there is a way to provide more descriptive deprecation warnings...

Comment (rawls238) [inline src/DataStructures.jl]: we could explicitly call depwarn, but the intended behavior of `iter` was to provide an iterable collection not an array copy of the contents of the stack / queue so it wouldn't be unreasonable to break the latter. I wonder if it would make sense to PR to `Base` another `deprecate` macro that took a third argument with a custom deprecation message.

Either we'd need to use `collect` but provide clear deprecation warnings stating that you should just switch from `iter(s)` to `s` if you're using this for iteration but switch from `iter(s)` to `collect(s)` if you're just looking for a copy of the contents of `s` or we would need to switch to `s` and accept that this may potentially break existing use cases. FWIW, this method wasn't out in the wild for horribly long and I have doubts that people were using it for getting copies of the contents of the stack, but happy to hear additional opinions on this.

Comment (DanielArndt) [inline src/DataStructures.jl]: I agree it's not unreasonable to break it given the intended use case. I think either way there are downsides, and it's one of those scenarios where you lose something either way. 

No strong feelings, so do what feels right.

Comment (rawls238) [inline src/DataStructures.jl]: going to leave as is

**Comment by rawls238** [comment]
thanks for reviewing this @kmsquire, @DanielArndt
